In [1]:
import numpy as np

# 1. Create a sample 2D dataset matrix (rows = samples, columns = features)

In [2]:
M = np.array([
    [65, 170, 75],
    [70, 180, 80],
    [60, 165, 70],
    [75, 175, 85]
])

print("Original Matrix:\n", M)

Original Matrix:
 [[ 65 170  75]
 [ 70 180  80]
 [ 60 165  70]
 [ 75 175  85]]


# 2. Compute mean and standard deviation for each feature (column-wise)

In [3]:
mean = M.mean(axis=0)
std = M.std(axis=0)

print("\nMean of each feature:\n", mean)
print("Standard deviation of each feature:\n", std)


Mean of each feature:
 [ 67.5 172.5  77.5]
Standard deviation of each feature:
 [5.59016994 5.59016994 5.59016994]


# 3. Perform scaling: (M - mean) / std

In [4]:
M_scaled = (M - mean) / std

# 4. Output the scaled matrix

In [5]:
print("\nScaled Matrix (Standardized Data):\n", M_scaled)


Scaled Matrix (Standardized Data):
 [[-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   1.34164079  0.4472136 ]
 [-1.34164079 -1.34164079 -1.34164079]
 [ 1.34164079  0.4472136   1.34164079]]
