 # From Data to Matrix

# Objective: Convert a raw dataset into a NumPy matrix and perform basic transformations.

In [1]:
import numpy as np

# 1. Create Raw Data

In [7]:
# Represent student grades as [name, math_score, science_score]
students = [
    ["Abisha", 85, 90],
    ["Senthil", 78, 82],
    ["Tamil", 92, 88],
    ["prathisha", 75, 80]
]

In [3]:
# Extract only the numerical part (scores)
scores = [row[1:] for row in students]

In [4]:
# 2. Convert to Matrix
score_matrix = np.array(scores)
print("Original Score Matrix:\n", score_matrix)

Original Score Matrix:
 [[85 90]
 [78 82]
 [92 88]
 [75 80]]


# 3(a). Add a new feature — sports_score

In [6]:
sports_score = np.array([[88], [75], [95], [70]])  # column vector
score_with_sports = np.hstack((score_matrix, sports_score))
print("\nMatrix After Adding Sports Score:\n", score_with_sports)


Matrix After Adding Sports Score:
 [[85 90 88]
 [78 82 75]
 [92 88 95]
 [75 80 70]]


# 3(b). Calculate a new feature — average score

In [8]:
average_score = np.mean(score_with_sports, axis=1).reshape(-1, 1)
score_with_average = np.hstack((score_with_sports, average_score))
print("\nMatrix After Adding Average Score:\n", score_with_average)


Matrix After Adding Average Score:
 [[85.         90.         88.         87.66666667]
 [78.         82.         75.         78.33333333]
 [92.         88.         95.         91.66666667]
 [75.         80.         70.         75.        ]]


# 3(c). Scale a feature — increase math scores by 10%

In [9]:
scaled_matrix = score_with_average.copy()
scaled_matrix[:, 0] = scaled_matrix[:, 0] * 1.1
print("\nMatrix After Scaling Math Scores by 10%:\n", scaled_matrix)


Matrix After Scaling Math Scores by 10%:
 [[ 93.5         90.          88.          87.66666667]
 [ 85.8         82.          75.          78.33333333]
 [101.2         88.          95.          91.66666667]
 [ 82.5         80.          70.          75.        ]]


# 4. Output comparison

In [11]:
print("\n--- Summary ---")
print("Original Matrix:\n", score_matrix)
print("\nTransformed Matrix:\n", scaled_matrix)


--- Summary ---
Original Matrix:
 [[85 90]
 [78 82]
 [92 88]
 [75 80]]

Transformed Matrix:
 [[ 93.5         90.          88.          87.66666667]
 [ 85.8         82.          75.          78.33333333]
 [101.2         88.          95.          91.66666667]
 [ 82.5         80.          70.          75.        ]]
