# Data centering and scaling

 Center and scale a dataset (matrix) to have a mean of 0 and a
standard deviation of 1 for each column

improt libraray

In [1]:
import numpy as np


In [2]:
# Create a sample 2D matrix (e.g., 5 rows, 3 columns)
# The random numbers have different means and scales
X = np.array([
    [10, 200, 3],
    [12, 180, 4],
    [8, 220, 2],
    [15, 250, 6],
    [9, 190, 3]
])

print("Original Matrix (X):")
print(X)


Original Matrix (X):
[[ 10 200   3]
 [ 12 180   4]
 [  8 220   2]
 [ 15 250   6]
 [  9 190   3]]


In [3]:
# Calculate the mean of each column
column_means = X.mean(axis=0)
print("\nMean of each column:")
print(column_means)



Mean of each column:
[ 10.8 208.    3.6]


In [4]:
# Calculate the standard deviation of each column

column_stds = X.std(axis=0)

print("\nStandard deviation of each column:")

print(column_stds)



Standard deviation of each column:
[ 2.48193473 24.81934729  1.356466  ]
