In [1]:
import numpy as np

# Step 1: Create a sample 2D grayscale "image" array

In [3]:
image = np.array([
    [10, 20, 30, 40],
    [20, 30, 40, 50],
    [30, 40, 50, 60],
    [40, 50, 60, 70]
], dtype=float)

print("Original Image:\n", image)

Original Image:
 [[10. 20. 30. 40.]
 [20. 30. 40. 50.]
 [30. 40. 50. 60.]
 [40. 50. 60. 70.]]


# Step 2: Prepare an empty array for the blurred result

In [4]:
blurred = np.zeros_like(image)

# Step 3: Apply blur using a 3x3 average filter (manual convolution)

In [5]:
for i in range(1, image.shape[0] - 1):        # avoid borders
    for j in range(1, image.shape[1] - 1):
        # extract 3x3 neighborhood
        neighborhood = image[i-1:i+2, j-1:j+2]
        # compute average
        blurred[i, j] = np.mean(neighborhood)

# Step 4: Display the blurred image

In [6]:
print("\nBlurred Image:\n", blurred)


Blurred Image:
 [[ 0.  0.  0.  0.]
 [ 0. 30. 40.  0.]
 [ 0. 40. 50.  0.]
 [ 0.  0.  0.  0.]]
