In [52]:
import numpy as np

# Step 1: Create a sample 2D array

In [54]:
arr = np.array([[10, 20, 30],
                [15, 25, 35],
                [20, 30, 40],
                [25, 35, 45]])

print("Original Array:\n", arr)

Original Array:
 [[10 20 30]
 [15 25 35]
 [20 30 40]
 [25 35 45]]


# Step 2: Compute mean and std for each column (axis=0)

In [55]:
mean = arr.mean(axis=0)
std = arr.std(axis=0)

print("\nColumn-wise Mean:\n", mean)
print("\nColumn-wise Standard Deviation:\n", std)


Column-wise Mean:
 [17.5 27.5 37.5]

Column-wise Standard Deviation:
 [5.59016994 5.59016994 5.59016994]


# Step 3: Normalize the data

In [56]:
normalized_arr = (arr - mean) / std

# Step 4: Display normalized data

In [57]:
print("\nNormalized Array (Z-score normalization):\n", normalized_arr)


Normalized Array (Z-score normalization):
 [[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
