In [1]:
import numpy as np

In [2]:
# 1. Create a Sample Array
# Generate a 2D array with shape (5, 4) and random integers between 10 and 100
arr = np.random.randint(10, 100, size=(5, 4))
print("Original Array:\n", arr)

Original Array:
 [[85 78 12 76]
 [30 31 25 75]
 [40 36 55 13]
 [16 11 31 94]
 [86 22 82 67]]


# 2. Calculations
# Mean of each column

In [ ]:

col_mean = arr.mean(axis=0)
print("\nMean of each column:", 
col_mean)


Mean of each column: [51.4 35.6 41.  65. ]


# Maximum value in each row

In [5]:
row_max = arr.max(axis=1)
print("Maximum value in each row:", row_max)


Maximum value in each row: [85 75 55 94 86]


# Total sum of all elements

In [6]:
total_sum = arr.sum()
print("Total sum of all elements:",
 total_sum)

Total sum of all elements: 965


# 3. Indexing
# Select first two rows and last two columns

In [7]:
sliced_arr = arr[0:2, 2:4]
print("\nFirst two rows and last two columns:\n",
 sliced_arr)


First two rows and last two columns:
 [[12 76]
 [25 75]]


# Boolean indexing — elements greater than 50

In [8]:
greater_than_50 = arr[arr > 50]
print("Elements greater than 50:", greater_than_50)

Elements greater than 50: [85 78 76 75 55 94 86 82 67]


# 4. Output

In [9]:
print("\nSummary of Calculations:")
print("------------------------")
print(f"Column Means: {col_mean}")
print(f"Row Maximums: {row_max}")
print(f"Total Sum: {total_sum}")
print(f"Sliced Array (0:2, 2:4):\n{sliced_arr}")
print(f"Elements > 50: {greater_than_50}")


Summary of Calculations:
------------------------
Column Means: [51.4 35.6 41.  65. ]
Row Maximums: [85 75 55 94 86]
Total Sum: 965
Sliced Array (0:2, 2:4):
[[12 76]
 [25 75]]
Elements > 50: [85 78 76 75 55 94 86 82 67]
